### ISSUE TITLE
Not compatible with std::swap

### ISSUE THREAD

**Issue by brucedjones** [jaredhoberock/managed_allocator#2]
At least in Visual Studio 2015. If a call is made to swap to vectors, both with managed allocators, the following error is thrown by the compiler.

binary '==': no operator found which takes a left-hand operand of type 'const managed_allocator<double>' (or there is no acceptable conversion)

**Comment by jaredhoberock** [comment]
Thanks for the report. I've added `operator==` and `operator!=`, let me know if that resolves the issue.

**Comment by brucedjones** [comment]
Thanks for the fix! It has resolved the issue.
