### ISSUE TITLE
Does not compile on VS2015

### ISSUE THREAD

**Issue by danwanban** [jaredhoberock/managed_allocator#3]
Hi,

Tries to compile on VS2015, Cuda8, narrowed to:
template<class T>
using managed_vector = std::vector<T, managed_allocator<T>>;
int main() {
	managed_vector<int> vec(n);
}

Got:
no suitable user-defined conversion from "std::_Wrap_alloc<managed_allocator<int>>" to "managed_allocator<std::_Container_proxy>" exists	Testers	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0	951	

Any ideas ?

**Comment by jaredhoberock** [comment]
I'm not sure what the problem is. It's possible that the problem is that the STL shipped with VS2015 is more strict about enforcing allocator requirements than are other implementations.

I took a wild guess at what might be missing from `managed_allocator` in this branch: https://github.com/jaredhoberock/managed_allocator/tree/issue-3

Let me know if you get a different result with those changes.

**Comment by danwanban** [comment]
Works !
Thanks for quick and effective help. 

Note: My code works fine with the fix, so I do not research this further, but if you compile the sample program in your project it shows some warnings:  

>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(53): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(57): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(59): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(53): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(57): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(59): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(146): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/sequential/for_each.h(83): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/sequential/for_each.h(84): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/detail/internal_functional.h(51): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/generic/logical.h(39): warning : calling a __host__ function from a __host__ __device__ function is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(153): warning : calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(153): warning : calling a __host__ function("std::_Iterator_base12::~_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::~_Iterator_base12 [subobject]") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(53): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator +=") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , unsigned int> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(57): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator *") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , unsigned int> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(59): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator +=") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , unsigned int> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(53): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator +=") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , long long> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(57): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator *") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , long long> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/cuda/detail/for_each.inl(59): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator +=") from a __host__ __device__ function("thrust::system::cuda::detail::for_each_n_detail::for_each_kernel::operator ()< ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::thrust::detail::wrapped_function< ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > , void> , long long> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/detail/internal_functional.h(51): warning : calling a __host__ function("") from a __host__ __device__ function("thrust::detail::unary_negate< ::> ::operator ()<int> ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/sequential/for_each.h(83): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator *") from a __host__ __device__ function("thrust::system::detail::sequential::for_each_n< ::thrust::detail::seq_t,  ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > , long long,  ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > > ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/sequential/for_each.h(84): warning : calling a __host__ function("std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator ++") from a __host__ __device__ function("thrust::system::detail::sequential::for_each_n< ::thrust::detail::seq_t,  ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > , long long,  ::thrust::detail::device_generate_functor< ::thrust::detail::fill_functor<int> > > ") is not allowed
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust/system/detail/generic/logical.h(39): warning : calling a __host__ function("std::_Vector_const_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ::operator ==") from a __host__ __device__ function("thrust::system::detail::generic::all_of< ::thrust::system::cpp::detail::par_t,  ::std::_Vector_iterator< ::std::_Vector_val< ::std::_Simple_types<int> > > ,  ::> ") is not allowed

**Comment by jaredhoberock** [comment]
@brycelelbach at one point the code in this repository composed cleanly with Thrust and the usage in the demonstration code generated neither warnings nor errors. It might be worthwhile to root cause the source of the errors and see if anything can be done to restore compatibility with Thrust.
